import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sharp Upholstery - Custom Work - Castlegar, BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <div className={styles.page}>
        <header className={styles.header}>
          <Link href="/" className={styles.logo}>
            <Image
              src="/svgs/sharp-logo-rect-no-border.svg"
              alt="Sharp Upholstery"
              width={782}
              height={286}
              priority
            />
          </Link>
          {/* Contact */}
          <div className={`${styles.finePrint} ${styles.contactInfo}`}>
            <a href="tel:2503067810">
              <strong className={styles.upperCase}>Phone</strong>{" "}
              <span>(250) 306-7810</span>
            </a>

            <a href="mailto:email@email.com">
              <strong className={styles.upperCase}>Email</strong>{" "}
              <span>email@email.com</span>
            </a>
          </div>
        </header>
        <main className={styles.main}></main>
        <footer className={styles.footer}>
          {/* Address */}
          <div className={styles.infoList}>
            <ul>
              <li>
                <h4 className={styles.upperCase}>Address</h4>
              </li>
              <li>
                <address className={styles.finePrint}>
                  191b Columbia Ave
                  <br />
                  Castlegar, BC
                  <br />
                  V1N 1A8
                </address>
              </li>
            </ul>
          </div>
          {/* SContact Movbile */}
          <div className={`${styles.infoList} ${styles.contactInfoMobile}`}>
            <ul>
              <li>
                <h4 className={styles.upperCase}>Contact</h4>
              </li>
              <li className={styles.finePrint}>
                <a href="tel:2503067810">
                  <strong>Phone:</strong> <span>(250) 306-7810</span>
                </a>
              </li>
              <li className={styles.finePrint}>
                <a href="mailto:email@email.com">
                  <strong>Email:</strong> <span>email@email.com</span>
                </a>
              </li>
            </ul>
          </div>
          {/* Shop Hours */}
          <div className={styles.infoList}>
            <ul>
              <li>
                <h4 className={styles.upperCase}>Shop Hours</h4>
              </li>
              <li className={styles.finePrint}>
                <strong>Monday - Friday:</strong> <span>8:00am - 5:00pm</span>
              </li>
              <li className={styles.finePrint}>
                <strong>Saturday:</strong> <span>10:00am - 5:00pm</span>
              </li>
              <li className={styles.finePrint}>
                <strong>Sundays & Holidays:</strong> <span>Closed</span>
              </li>
            </ul>
          </div>
        </footer>
      </div>
    </>
  );
}
